#!/bin/sh

sudo apt install \
    clang-format \
    cmake \
    libyaml-cpp-dev \
    libboost-all-dev \
    libopencv-dev \
    qt5-default \
    python3-pip \
    python3-matplotlib \
    python3-numpy

sudo pip3 install conan
